psql -a -b -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c "
    CREATE ROLE ${POSTGREST_ANON_ROLE} nologin;
    CREATE ROLE ${POSTGREST_AUTHENTICATOR} noinherit login password '${POSTGREST_AUTHENTICATOR_PASSWORD}';
    GRANT ${POSTGREST_ANON_ROLE} TO ${POSTGREST_AUTHENTICATOR};

"